name: Build wheels 2

on:
  workflow_dispatch:
    inputs:
      runs-on:
        description: "The runner to use for the build"
        required: true
        type: string
        default: ubuntu-22.04
      python-version:
        description: "The Python version to use for the build"
        required: true
        type: string
      cuda-version:
        description: "The CUDA version to use for the build"
        required: true
        type: string
      torch-version:
        description: "The PyTorch version to use for the build"
        required: true
        type: string
      cxx11-abi:
        description: "The C++11 ABI to use for the build"
        required: true
        type: string
      upload-to-release:
        description: "Upload wheel to this release"
        required: false
        type: boolean
        default: false
      release-version:
        description: "Upload wheel to this release"
        required: false
        type: string
  push:

jobs:
  build-wheels:
    uses: ./.github/workflows/_build.yml
    with:
      runs-on: ubuntu-22.04 # ${{ inputs.runs-on }}
      python-version: 3.12 # ${{ inputs.python-version }}
      cuda-version: 12.9.1 # ${{ inputs.cuda-version }}
      torch-version: 2.8.0 # ${{ inputs.torch-version }}
      cxx11-abi: TRUE # ${{ inputs.cxx11-abi }}
      upload-to-release: false
      release-version: ${{ inputs.release-version }}