name: Test FA3 Build

on:
  workflow_dispatch:
    inputs:
      python-version:
        description: 'Python version'
        required: true
        default: '3.10'
        type: choice
        options:
          - '3.9'
          - '3.10'
          - '3.11'
          - '3.12'
      torch-version:
        description: 'PyTorch version'
        required: true
        default: '2.5.1'
        type: choice
        options:
          - '2.4.0'
          - '2.5.1'
          - '2.6.0'
          - '2.7.1'
          - '2.8.0'
      cuda-version:
        description: 'CUDA version'
        required: true
        default: '12.9.1'
      cxx11_abi:
        description: 'C++11 ABI'
        required: true
        default: 'FALSE'
        type: choice
        options:
          - 'FALSE'
          - 'TRUE'

jobs:
  test_build:
    uses: ./.github/workflows/_build.yml
    with:
      runs-on: ubuntu-22.04
      python-version: ${{ inputs.python-version }}
      cuda-version: ${{ inputs.cuda-version }}
      torch-version: ${{ inputs.torch-version }}
      cxx11_abi: ${{ inputs.cxx11_abi }}
      release-version: 'test-fa3'
      upload-to-release: false
      is-fa3: 'true'